@SistemaDeInvestigacion.Server_HostAddress = http://localhost:5091

GET {{SistemaDeInvestigacion.Server_HostAddress}}/weatherforecast/
Accept: application/json


###

GET {{SistemaDeInvestigacion.Server_HostAddress}}/api/auth/login/
Accept: application/json


###

